### ISSUE TITLE
add dropdown option for Artillery targeting remote 

### ISSUE THREAD

**Issue by Agrrox** [ickputzdirwech/Shortcuts-ick#7]
![Screen Shot 2022-01-10 at 03 27 24](https://user-images.githubusercontent.com/10901821/148713591-a8df86d7-af72-44c6-a97f-7b0db5e48ac2.png)

**Comment by ickputzdirwech** [comment]
Thanks again for the suggestion but again I won't do this. I only added the special case for the spidertron because depending on your use case it might be reasonable to have multiple spidertron remotes in your inventory. I can't imagine cases when this would be useful for things like the artillery targeting remote or the discharge defense remote. You can of course try to convince me otherwise :)
